version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://localhost:3001
    networks:
      - h1_network
    restart: unless-stopped

networks:
  h1_network:
    driver: bridge 