version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /home/unitree:/home/unitree:rw
      - ./backend:/app:rw
      - /dev:/dev:ro
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ROOT_PATH=/home/unitree
    privileged: true
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 