version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: h1-frontend
    restart: unless-stopped
    networks:
      - h1-network

networks:
  h1-network:
    driver: bridge 